In [ ]:
import numpy as np
a = np.int8(25) #выбран формат данных целое число и 8 -число бит, которое отведено для переменной а
print(a)

25


In [4]:
print(type(a))

<class 'numpy.int8'>


In [8]:
#функция которая показывает возможности того или иного типа данных
np.iinfo(a) 
np.iinfo(np.int8) 

iinfo(min=-128, max=127, dtype=int8)

In [83]:
#в numpy есть беззнаковые числа (неотрицательные) u - unsigned
b = np.uint8(124)
print(b)
print(type(b))
np.iinfo(b) 

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [22]:
a =np.int32(1000)
print(a)
print(type(a))
a = np.int32(2056)
print(a)
print(type(a))
print(np.iinfo(np.int32))
print(np.iinfo(np.uint32))

1000
<class 'numpy.int32'>
2056
<class 'numpy.int32'>
Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for uint32
---------------------------------------------------------------
min = 0
max = 4294967295
---------------------------------------------------------------



In [82]:
#если мы к нумпаевскому числу прибави обычное, то формат данных поменяетс на дефолтный для нумпаевскзи чисел
a = np.int16(1000)
b = a+10000
print(b)
print(type(b))

11000
<class 'numpy.int16'>


In [81]:
a = np.int16(1000)
b = np.int32(25)
c = a+b
print(c, type(c))
print

1025 <class 'numpy.int32'>


<function print>

In [80]:
a = np.uint8(255)
print(a)

255


In [58]:
np.finfo(np.float16)
print(np.finfo(np.float16))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------



In [ ]:
#узнаем как сохраняется точность при float16
print(np.float16(4.12))
print(np.float16(4.13))
print(np.float16(4.123))
print(np.float16(4.124))
print(np.float16(4.125))

4.12
4.13
4.12
4.125
4.125


In [60]:
print(np.sctypeDict)
print(len(np.sctypeDict))

{'bool': <class 'numpy.bool'>, 'float16': <class 'numpy.float16'>, 'float32': <class 'numpy.float32'>, 'float64': <class 'numpy.float64'>, 'longdouble': <class 'numpy.longdouble'>, 'complex64': <class 'numpy.complex64'>, 'complex128': <class 'numpy.complex128'>, 'clongdouble': <class 'numpy.clongdouble'>, 'bytes_': <class 'numpy.bytes_'>, 'str_': <class 'numpy.str_'>, 'void': <class 'numpy.void'>, 'object_': <class 'numpy.object_'>, 'datetime64': <class 'numpy.datetime64'>, 'timedelta64': <class 'numpy.timedelta64'>, 'int8': <class 'numpy.int8'>, 'byte': <class 'numpy.int8'>, 'uint8': <class 'numpy.uint8'>, 'ubyte': <class 'numpy.uint8'>, 'int16': <class 'numpy.int16'>, 'short': <class 'numpy.int16'>, 'uint16': <class 'numpy.uint16'>, 'ushort': <class 'numpy.uint16'>, 'intc': <class 'numpy.intc'>, 'uintc': <class 'numpy.uintc'>, 'int32': <class 'numpy.int32'>, 'long': <class 'numpy.int32'>, 'uint32': <class 'numpy.uint32'>, 'ulong': <class 'numpy.uint32'>, 'int64': <class 'numpy.int64'

In [66]:
#В numpy используется несколько другой тип данных для bool
a = True
print(type(a))
a = np.bool(a)
print(type(a))


<class 'bool'>
<class 'numpy.bool'>


In [77]:
np.iinfo(np.int64)
print(np.iinfo(np.uint32))


Machine parameters for uint32
---------------------------------------------------------------
min = 0
max = 4294967295
---------------------------------------------------------------



In [78]:
a = np.int32(1000)
print(a)
# 1000
print(type(a))
# <class 'numpy.int32'>
a = 2056
print(a)
# 2056
print(type(a))
# <class 'int'>

1000
<class 'numpy.int32'>
2056
<class 'int'>


In [135]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(a + b)
# -81
# RuntimeWarning: overflow encountered in int_scalars
# Переполнено int'овое значение

2147483610 2147483605
-81


C:\Users\Сергей\AppData\Local\Temp\ipykernel_1316\2257502981.py:5: RuntimeWarning: overflow encountered in scalar add
  print(a + b)


In [85]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(np.int64(a) + np.int64(b))
# 4294967215

2147483610 2147483605
4294967215


In [86]:
a = True
print(type(a))
# <class 'bool'>
a = np.bool(a)
print(type(a))
# <class 'bool'>
a = np.bool_(a)
print(type(a))
# <class 'numpy.bool_'>
 
# Значения равны
print(np.bool(True) == np.bool_(True))
# True
# А типы — нет:
print(type(np.bool(True)) == type(np.bool_(True)))
# False

<class 'bool'>
<class 'numpy.bool'>
<class 'numpy.bool'>
True
True


In [148]:

print(np.iinfo(np.uint8))


Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------



In [149]:
a = np.int8(-123)
print(a)
b= np.uint8(a)
print(b)

-456%15




-123
133


9

## Массивы

In [150]:
import numpy as np
arr = np.array([1,5,2,9,1])
arr

array([1, 5, 2, 9, 1])

In [151]:
# Функция np.array возвращает объекты типа numpy.ndarray:

print(type(arr))
# <class 'numpy.ndarray'>
# Название ndarray — это сокращение от n-dimensional array, n-мерный массив.

<class 'numpy.ndarray'>


In [146]:
# Перечислить список из списков можно
# было и в одну строку, но на нескольких
# строках получается нагляднее
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr
# array([[12, 45, 78],
#        [34, 56, 13],
#        [12, 98, 76]])

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [147]:
arr = np.array([1,5,2,9,10])
arr.dtype
# dtype('int64')

dtype('int64')

In [160]:
#  Задать тип данных сразу при создании массива можно с помощью параметра dtype:

arr = np.array([1,5,2,9,10], dtype=np.int64)
arr
# array([ 1,  5,  2,  9, 10], dtype=int8)

array([ 1,  5,  2,  9, 10])

In [161]:
# Теперь, если добавить в arr число больше 127 или меньше -128, оно потеряет исходное значение, как и при преобразовании к меньшему типу:

arr[2] = 2000
arr
# array([  1,   5, -48,   9,  10], dtype=int8)

array([   1,    5, 2000,    9,   10])

In [166]:
np.finfo(np.float32)
print(np.finfo(np.float32))

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------



In [191]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float64)
print(arr.dtype)
arr

float64


array([ 3.4523400e+05,  8.7636212e+05,  0.0000000e+00, -1.0000000e+03,
        9.9999999e+07])

In [ ]:
print(np.sctypeDict)
print(len(np.sctypeDict))
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

In [ ]:
#Зададим 2 массива: одномерный и двухмерный
arr = np.array([1,5,2,9,10], dtype=np.int8)

nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [199]:
#Выведем размерность массива
arr.ndim
# 1
nd_arr.ndim
# 2

2

In [200]:
#Узнаем общее число элементов
arr.size
# 1
nd_arr.size
# 2

9

In [ ]:
# Форма или структура массива хранится в атрибуте .shape:
arr.shape
# (5,)
nd_arr.shape
# (3, 3)

(3, 3)

In [203]:
# Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:
# Действительно, в arr хранятся числа в виде int8 (8 бит => 1 байт), а в nd_arr — в виде int16 (16 бит => 2 байта).
arr.itemsize
# 1
nd_arr.itemsize
# 2

2

In [204]:
# Создадим одномерный массив из пяти элементов:

zeros_1d = np.zeros(5)
zeros_1d
# array([0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0.])

In [205]:
# Создадим трёхмерный массив с формой 5x4x3 и типом float32:

zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
# (5, 4, 3)

(5, 4, 3)


In [207]:
# Поэкспериментируем. Создадим массив из пяти чисел от 0 до 4:

np.arange(5)
# array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [ ]:
# Создадим массив от 2.5 до 5:
np.arange(2.5, 5)
# array([2.5, 3.5, 4.5])

array([2.5, 3.5, 4.5])

In [ ]:
# Создадим массив от 2.5 до 5 с шагом 0.5:
np.arange(2.5, 5, 0.5)
# array([2.5, 3. , 3.5, 4. , 4.5])

array([2.5, 3. , 3.5, 4. , 4.5])

In [219]:
# Создадим массив от 2.5 до 5 с шагом 0.5 и с типом float16:

np.arange(2.5, 5, 0.5, dtype=np.float16)
# array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

## linspace

In [220]:
# Давайте потренируемся. Создадим массив из десяти чисел между 1 и 2:

arr = np.linspace(1, 2, 10)
arr
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [231]:
# Создадим массив из десяти чисел между 1 и 2, не включая 2:

arr = np.linspace(1, 2, 10, endpoint=False)
arr
# array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [222]:
# Узнаем, какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось:

arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
# 0.1111111111111111

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)
# 0.1

0.1111111111111111
0.1


In [ ]:
# Задание 6.6
# С каким шагом сгенерируется массив из 60 чисел от -6 до 21 включительно? Ответ округлите до двух знаков после точки.
arr, step = np.linspace(-6, 21, 60, endpoint=True, retstep=True)
print(arr)
print(step)

In [235]:
# С каким шагом сгенерируется массив из 60 чисел от -6 до 21 невключительно? Ответ округлите до двух знаков после точки.
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(arr)
print(step)

[-6.   -5.55 -5.1  -4.65 -4.2  -3.75 -3.3  -2.85 -2.4  -1.95 -1.5  -1.05
 -0.6  -0.15  0.3   0.75  1.2   1.65  2.1   2.55  3.    3.45  3.9   4.35
  4.8   5.25  5.7   6.15  6.6   7.05  7.5   7.95  8.4   8.85  9.3   9.75
 10.2  10.65 11.1  11.55 12.   12.45 12.9  13.35 13.8  14.25 14.7  15.15
 15.6  16.05 16.5  16.95 17.4  17.85 18.3  18.75 19.2  19.65 20.1  20.55]
0.45


## Изменение формы массива

In [ ]:
# Создадим массив из восьми чисел:

import numpy as np
arr = np.arange(8)
arr
# array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой:

arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

In [ ]:
# Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию reshape. Она также принимает в качестве аргумента кортеж из чисел для формы, но возвращает новый массив, а не изменяет исходный:

arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new
# array([[0, 1, 2, 3],
#       [4, 5, 6, 7]])

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new
# array([[0, 2, 4, 6],
#       [1, 3, 5, 7]])

In [ ]:
# Будем работать с двумерным массивом:

arr = np.arange(8)
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])


(3,)
(3,)


In [243]:
# Транспонируем его:

arr = np.arange(8)
arr.shape = (2, 4)
arr_trans = arr.transpose()
arr_trans
# array([[0, 4],
#        [1, 5],
#        [2, 6],
#        [3, 7]])


array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [244]:

# При транспонировании одномерного массива его форма не меняется:

arr = np.arange(3)
print(arr.shape)
# (3,)
arr_trans = arr.transpose()
print(arr_trans.shape)
# (3,)

(3,)
(3,)


## Срезы массивов

In [245]:
arr = np.linspace(1, 2, 6)
arr
# array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [246]:
print(arr[2])
# 1.4

1.4


In [247]:
print(arr[2:4])
# [1.4 1.6]

[1.4 1.6]


In [248]:
print(arr[::-1])
# [2.  1.8 1.6 1.4 1.2 1. ]

[2.  1.8 1.6 1.4 1.2 1. ]


In [249]:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array
# array([[0. , 0.5, 1. , 1.5],
#        [2. , 2.5, 3. , 3.5],
#        [4. , 4.5, 5. , 5.5]])

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [250]:
nd_array[1][2]
# 3.0

np.float64(3.0)

In [251]:
nd_array[1, 2]

np.float64(3.0)

In [252]:
nd_array[:2, 2]
# array([1., 3.])

array([1., 3.])

In [253]:
nd_array[1:, 2:4]
# array([[3. , 3.5],
#       [5. , 5.5]])

array([[3. , 3.5],
       [5. , 5.5]])

In [254]:
nd_array[:, 2:4]
# array([[1. , 1.5],
#       [3. , 3.5],
#       [5. , 5.5]])

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [255]:
nd_array[:2]
# array([[0. , 0.5, 1. , 1.5],
#       [2. , 2.5, 3. , 3.5]])

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [ ]:
# Задание 7.2
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)