In [ ]:
import numpy as np
a = np.int8(25) #выбран формат данных целое число и 8 -число бит, которое отведено для переменной а
print(a)

25


In [4]:
print(type(a))

<class 'numpy.int8'>


In [8]:
#функция которая показывает возможности того или иного типа данных
np.iinfo(a) 
np.iinfo(np.int8) 

iinfo(min=-128, max=127, dtype=int8)

In [83]:
#в numpy есть беззнаковые числа (неотрицательные) u - unsigned
b = np.uint8(124)
print(b)
print(type(b))
np.iinfo(b) 

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [22]:
a =np.int32(1000)
print(a)
print(type(a))
a = np.int32(2056)
print(a)
print(type(a))
print(np.iinfo(np.int32))
print(np.iinfo(np.uint32))

1000
<class 'numpy.int32'>
2056
<class 'numpy.int32'>
Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for uint32
---------------------------------------------------------------
min = 0
max = 4294967295
---------------------------------------------------------------



In [82]:
#если мы к нумпаевскому числу прибави обычное, то формат данных поменяетс на дефолтный для нумпаевскзи чисел
a = np.int16(1000)
b = a+10000
print(b)
print(type(b))

11000
<class 'numpy.int16'>


In [81]:
a = np.int16(1000)
b = np.int32(25)
c = a+b
print(c, type(c))
print

1025 <class 'numpy.int32'>


<function print>

In [80]:
a = np.uint8(255)
print(a)

255


In [58]:
np.finfo(np.float16)
print(np.finfo(np.float16))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------



In [ ]:
#узнаем как сохраняется точность при float16
print(np.float16(4.12))
print(np.float16(4.13))
print(np.float16(4.123))
print(np.float16(4.124))
print(np.float16(4.125))

4.12
4.13
4.12
4.125
4.125


In [60]:
print(np.sctypeDict)
print(len(np.sctypeDict))

{'bool': <class 'numpy.bool'>, 'float16': <class 'numpy.float16'>, 'float32': <class 'numpy.float32'>, 'float64': <class 'numpy.float64'>, 'longdouble': <class 'numpy.longdouble'>, 'complex64': <class 'numpy.complex64'>, 'complex128': <class 'numpy.complex128'>, 'clongdouble': <class 'numpy.clongdouble'>, 'bytes_': <class 'numpy.bytes_'>, 'str_': <class 'numpy.str_'>, 'void': <class 'numpy.void'>, 'object_': <class 'numpy.object_'>, 'datetime64': <class 'numpy.datetime64'>, 'timedelta64': <class 'numpy.timedelta64'>, 'int8': <class 'numpy.int8'>, 'byte': <class 'numpy.int8'>, 'uint8': <class 'numpy.uint8'>, 'ubyte': <class 'numpy.uint8'>, 'int16': <class 'numpy.int16'>, 'short': <class 'numpy.int16'>, 'uint16': <class 'numpy.uint16'>, 'ushort': <class 'numpy.uint16'>, 'intc': <class 'numpy.intc'>, 'uintc': <class 'numpy.uintc'>, 'int32': <class 'numpy.int32'>, 'long': <class 'numpy.int32'>, 'uint32': <class 'numpy.uint32'>, 'ulong': <class 'numpy.uint32'>, 'int64': <class 'numpy.int64'

In [66]:
#В numpy используется несколько другой тип данных для bool
a = True
print(type(a))
a = np.bool(a)
print(type(a))


<class 'bool'>
<class 'numpy.bool'>


In [77]:
np.iinfo(np.int64)
print(np.iinfo(np.uint32))


Machine parameters for uint32
---------------------------------------------------------------
min = 0
max = 4294967295
---------------------------------------------------------------



In [78]:
a = np.int32(1000)
print(a)
# 1000
print(type(a))
# <class 'numpy.int32'>
a = 2056
print(a)
# 2056
print(type(a))
# <class 'int'>

1000
<class 'numpy.int32'>
2056
<class 'int'>


In [135]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(a + b)
# -81
# RuntimeWarning: overflow encountered in int_scalars
# Переполнено int'овое значение

2147483610 2147483605
-81


C:\Users\Сергей\AppData\Local\Temp\ipykernel_1316\2257502981.py:5: RuntimeWarning: overflow encountered in scalar add
  print(a + b)


In [85]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(np.int64(a) + np.int64(b))
# 4294967215

2147483610 2147483605
4294967215


In [86]:
a = True
print(type(a))
# <class 'bool'>
a = np.bool(a)
print(type(a))
# <class 'bool'>
a = np.bool_(a)
print(type(a))
# <class 'numpy.bool_'>
 
# Значения равны
print(np.bool(True) == np.bool_(True))
# True
# А типы — нет:
print(type(np.bool(True)) == type(np.bool_(True)))
# False

<class 'bool'>
<class 'numpy.bool'>
<class 'numpy.bool'>
True
True


In [148]:

print(np.iinfo(np.uint8))


Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------



In [149]:
a = np.int8(-123)
print(a)
b= np.uint8(a)
print(b)

-456%15




-123
133


9

## Массивы

In [150]:
import numpy as np
arr = np.array([1,5,2,9,1])
arr

array([1, 5, 2, 9, 1])

In [151]:
# Функция np.array возвращает объекты типа numpy.ndarray:

print(type(arr))
# <class 'numpy.ndarray'>
# Название ndarray — это сокращение от n-dimensional array, n-мерный массив.

<class 'numpy.ndarray'>


In [146]:
# Перечислить список из списков можно
# было и в одну строку, но на нескольких
# строках получается нагляднее
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr
# array([[12, 45, 78],
#        [34, 56, 13],
#        [12, 98, 76]])

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [147]:
arr = np.array([1,5,2,9,10])
arr.dtype
# dtype('int64')

dtype('int64')

In [160]:
#  Задать тип данных сразу при создании массива можно с помощью параметра dtype:

arr = np.array([1,5,2,9,10], dtype=np.int64)
arr
# array([ 1,  5,  2,  9, 10], dtype=int8)

array([ 1,  5,  2,  9, 10])

In [161]:
# Теперь, если добавить в arr число больше 127 или меньше -128, оно потеряет исходное значение, как и при преобразовании к меньшему типу:

arr[2] = 2000
arr
# array([  1,   5, -48,   9,  10], dtype=int8)

array([   1,    5, 2000,    9,   10])

In [166]:
np.finfo(np.float32)
print(np.finfo(np.float32))

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------



In [191]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float64)
print(arr.dtype)
arr

float64


array([ 3.4523400e+05,  8.7636212e+05,  0.0000000e+00, -1.0000000e+03,
        9.9999999e+07])

In [ ]:
print(np.sctypeDict)
print(len(np.sctypeDict))
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

In [ ]:
#Зададим 2 массива: одномерный и двухмерный
arr = np.array([1,5,2,9,10], dtype=np.int8)

nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [199]:
#Выведем размерность массива
arr.ndim
# 1
nd_arr.ndim
# 2

2

In [200]:
#Узнаем общее число элементов
arr.size
# 1
nd_arr.size
# 2

9

In [ ]:
# Форма или структура массива хранится в атрибуте .shape:
arr.shape
# (5,)
nd_arr.shape
# (3, 3)

(3, 3)

In [203]:
# Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:
# Действительно, в arr хранятся числа в виде int8 (8 бит => 1 байт), а в nd_arr — в виде int16 (16 бит => 2 байта).
arr.itemsize
# 1
nd_arr.itemsize
# 2

2

In [204]:
# Создадим одномерный массив из пяти элементов:

zeros_1d = np.zeros(5)
zeros_1d
# array([0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0.])

In [205]:
# Создадим трёхмерный массив с формой 5x4x3 и типом float32:

zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
# (5, 4, 3)

(5, 4, 3)


In [207]:
# Поэкспериментируем. Создадим массив из пяти чисел от 0 до 4:

np.arange(5)
# array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [ ]:
# Создадим массив от 2.5 до 5:
np.arange(2.5, 5)
# array([2.5, 3.5, 4.5])

array([2.5, 3.5, 4.5])

In [ ]:
# Создадим массив от 2.5 до 5 с шагом 0.5:
np.arange(2.5, 5, 0.5)
# array([2.5, 3. , 3.5, 4. , 4.5])

array([2.5, 3. , 3.5, 4. , 4.5])

In [219]:
# Создадим массив от 2.5 до 5 с шагом 0.5 и с типом float16:

np.arange(2.5, 5, 0.5, dtype=np.float16)
# array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

## linspace

In [220]:
# Давайте потренируемся. Создадим массив из десяти чисел между 1 и 2:

arr = np.linspace(1, 2, 10)
arr
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [231]:
# Создадим массив из десяти чисел между 1 и 2, не включая 2:

arr = np.linspace(1, 2, 10, endpoint=False)
arr
# array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [222]:
# Узнаем, какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось:

arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
# 0.1111111111111111

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)
# 0.1

0.1111111111111111
0.1


In [ ]:
# Задание 6.6
# С каким шагом сгенерируется массив из 60 чисел от -6 до 21 включительно? Ответ округлите до двух знаков после точки.
arr, step = np.linspace(-6, 21, 60, endpoint=True, retstep=True)
print(arr)
print(step)

In [235]:
# С каким шагом сгенерируется массив из 60 чисел от -6 до 21 невключительно? Ответ округлите до двух знаков после точки.
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(arr)
print(step)

[-6.   -5.55 -5.1  -4.65 -4.2  -3.75 -3.3  -2.85 -2.4  -1.95 -1.5  -1.05
 -0.6  -0.15  0.3   0.75  1.2   1.65  2.1   2.55  3.    3.45  3.9   4.35
  4.8   5.25  5.7   6.15  6.6   7.05  7.5   7.95  8.4   8.85  9.3   9.75
 10.2  10.65 11.1  11.55 12.   12.45 12.9  13.35 13.8  14.25 14.7  15.15
 15.6  16.05 16.5  16.95 17.4  17.85 18.3  18.75 19.2  19.65 20.1  20.55]
0.45


## Изменение формы массива

In [ ]:
# Создадим массив из восьми чисел:

import numpy as np
arr = np.arange(8)
arr
# array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой:

arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

In [ ]:
# Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию reshape. Она также принимает в качестве аргумента кортеж из чисел для формы, но возвращает новый массив, а не изменяет исходный:

arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new
# array([[0, 1, 2, 3],
#       [4, 5, 6, 7]])

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new
# array([[0, 2, 4, 6],
#       [1, 3, 5, 7]])

In [ ]:
# Будем работать с двумерным массивом:

arr = np.arange(8)
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])


(3,)
(3,)


In [243]:
# Транспонируем его:

arr = np.arange(8)
arr.shape = (2, 4)
arr_trans = arr.transpose()
arr_trans
# array([[0, 4],
#        [1, 5],
#        [2, 6],
#        [3, 7]])


array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [244]:

# При транспонировании одномерного массива его форма не меняется:

arr = np.arange(3)
print(arr.shape)
# (3,)
arr_trans = arr.transpose()
print(arr_trans.shape)
# (3,)

(3,)
(3,)


Срезы массивов

In [245]:
arr = np.linspace(1, 2, 6)
arr
# array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [246]:
print(arr[2])
# 1.4

1.4


In [247]:
print(arr[2:4])
# [1.4 1.6]

[1.4 1.6]


In [248]:
print(arr[::-1])
# [2.  1.8 1.6 1.4 1.2 1. ]

[2.  1.8 1.6 1.4 1.2 1. ]


In [261]:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array
# array([[0. , 0.5, 1. , 1.5],
#        [2. , 2.5, 3. , 3.5],
#        [4. , 4.5, 5. , 5.5]])

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [250]:
nd_array[1][2]
# 3.0

np.float64(3.0)

In [251]:
nd_array[1, 2]

np.float64(3.0)

In [252]:
nd_array[:2, 2]
# array([1., 3.])

array([1., 3.])

In [262]:
nd_array[1:, 2:4]
# array([[3. , 3.5],
#       [5. , 5.5]])

array([[3. , 3.5],
       [5. , 5.5]])

In [254]:
nd_array[:, 2:4]
# array([[1. , 1.5],
#       [3. , 3.5],
#       [5. , 5.5]])

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [255]:
nd_array[:2]
# array([[0. , 0.5, 1. , 1.5],
#       [2. , 2.5, 3. , 3.5]])

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [301]:
# Задание 7.2
import numpy as np
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)
elem_5_3 = mystery[4,2]
last = mystery[-1,-1]
line_4 = mystery[3]
col_2 = mystery[0:6,-2]
part = mystery[1:4,2:5]
rev = (mystery[0:6,6])[::-1]
trans = mystery.transpose()

print(elem_5_3)
print(last)
print(line_4)
print(col_2)
print(part)
print(rev)
print(trans)

30305
-32037
[13240  7994 32592 20149 13754 11795  -564]
[-17182  15790  25397  11795  12578    -47]
[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]
[-32037  29943   -564   8225   7181 -18049]
[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


Сортировка массивов

In [297]:
# Способ 1. Функция np.sort(<массив>) возвращает новый отсортированный массив:

arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
# [23 12 45 12 23  4 15  3]
print(arr_new)
# [ 3  4 12 12 15 23 23 45]

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [298]:
# Способ 2. Функция <массив>.sort() сортирует исходный массив и возвращает None:

arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)
# [ 3  4 12 12 15 23 23 45]

None
[ 3  4 12 12 15 23 23 45]


Работа с пропущенными данными

In [ ]:
import numpy as np
data = np.array([4, 9, -4, 3])

In [302]:
roots = np.sqrt(data)
roots
# RuntimeWarning: invalid value encountered in sqrt
# array([2.        , 3.        ,        nan, 1.73205081])

C:\Users\Сергей\AppData\Local\Temp\ipykernel_1316\2040053643.py:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [304]:
sum(roots)
# nan

np.float64(nan)

In [305]:
np.isnan(roots)
# array([False, False,  True, False])

array([False, False,  True, False])

In [306]:
roots[np.isnan(roots)]
# array([nan])

array([nan])

In [308]:
# Этим элементам можно присвоить новые значения, например 0:

roots[np.isnan(roots)] = 0
roots
# array([2.        , 3.        , 0.        , 1.73205081])

array([2.        , 3.        , 0.        , 1.73205081])

In [309]:
sum(roots)
# 6.732050807568877

np.float64(6.732050807568877)

In [1]:
import numpy as np
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)
# Получите булевый массив nans_index с информацией о np.nan в массиве mystery: True - значение пропущено, False - значение не пропущено
nans_index=np.isnan(mystery)
n_nan=np.sum(np.isnan(mystery))
mystery_new = mystery.copy()
mystery_new[np.isnan(mystery_new)] = 0
mystery_int = np.int32(mystery)
array = np.sort(mystery)
table = array.reshape((5, 3), order='F')
col = table[:,1]
col

C:\Users\Сергей\AppData\Local\Temp\ipykernel_11728\286537341.py:10: RuntimeWarning: invalid value encountered in cast
  mystery_int = np.int32(mystery)


array([-2365., 12279., 16132., 25933., 28745.], dtype=float32)

Операции с векторами

In [2]:
# Произведём сложение двух векторов:

import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2
# array([14. , 10. , 10.6, 15.5])

array([14. , 10. , 10.6, 15.5])

In [3]:
# Что бы произошло при сложении двух списков? Их элементы просто объединились бы в один список:

list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2
# [2, 4, 7, 2.5, 12, 6, 3.6, 13]
# Чтобы сложить два этих списка поэлементно, нам пришлось бы написать списочное сокращение с применением функции zip():

[x + y for x, y in zip(list1, list2)]
# [14, 10, 10.6, 15.5]

[14, 10, 10.6, 15.5]

In [4]:
# Поэлементно умножим два вектора одинаковой длины:

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2
# array([24. , 24. , 25.2, 32.5])

array([24. , 24. , 25.2, 32.5])

In [ ]:
# Умножение вектора на число
vec = np.arange(5)
vec * 10
# array([ 0, 10, 20, 30, 40])
vec ** 2
# array([ 0,  1,  4,  9, 16])

In [5]:
# Также векторы можно сравнивать друг с другом поэлементно:

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
vec1 > vec2
# array([False, False,  True, False])

array([False, False,  True, False])

In [ ]:
# Аналогично можно сравнивать вектор с числом:

vec = np.array([14,15,9,26,53,5,89])
vec <= 26
# array([ True,  True,  True,  True, False,  True, False])

In [8]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
vec1 > vec2
# array([False, False,  True, False])

array([False, False,  True, False])

Продвинутые операции с векторами

In [9]:
vec = np.array([3, 4])

In [10]:
# Длина вектора
length = np.sqrt(np.sum(vec ** 2))
print(length)
# 5.0

5.0


In [ ]:
length = np.linalg.norm(vec)
print(length)
# 5.0

In [11]:
# Расстояние между двумя векторами, то есть расстояние между их концами, [в евклидовом пространстве] вычисляется как квадратный корень из суммы квадратов разностей соответствующих координат.
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance
# 12.206555615733702

np.float64(12.206555615733702)

In [12]:
# Или же можно вот так:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance
# 12.206555615733702

np.float64(12.206555615733702)

In [13]:
# скалярным произведением двух векторов называют сумму произведений их соответствующих координат.
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product
# 250.0

np.float64(250.0)

In [14]:
# или же вот так
scalar_product = np.dot(vec1, vec2)
scalar_product
# 250.0

np.float64(250.0)

In [ ]:
# Скалярное произведение также имеет широкое применение в математике и других операциях с векторами. В частности, равенство скалярного произведения нулю означает перпендикулярность рассматриваемых векторов:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

In [21]:
# Задание 8.4 узнаем сонаправлены ли векторы
a = np.array([23, 34, 27]) 
b = np.array([-54,   1,  46])
c = np.array([46, 68, 54])

length_a = np.linalg.norm(a)
length_b = np.linalg.norm(b)
length_c = np.linalg.norm(c)
sonapr_ab = np.linalg.norm(a)+np.linalg.norm(b) == np.linalg.norm(a+b)
sonapr_bc = np.linalg.norm(b)+np.linalg.norm(c) == np.linalg.norm(b+c)
sonapr_ac = np.linalg.norm(a)+np.linalg.norm(c) == np.linalg.norm(a+c)
print(sonapr_ab)
print(sonapr_bc)
print(sonapr_ac)

False
False
True


In [23]:
# Задание 8.5 найдем пару векторов расстоняие между которыми больше 100
a = np.array([23, 34, 27]) 
b = np.array([-54,   1,  46])
c = np.array([46, 68, 54])
distance_ab = np.linalg.norm(a-b)
distance_bc = np.linalg.norm(b-c)
distance_ac = np.linalg.norm(a-c)
print(distance_ab)
print(distance_bc)
print(distance_ac)


85.901105930017
120.6358155772986
49.13247398615299


In [24]:
# Задание 8.6. найдем перпендикулярные векторы
a = np.array([23, 34, 27]) 
b = np.array([-54,   1,  46])
c = np.array([46, 68, 54])
scalar_product_ab = np.dot(a,b)
scalar_product_bc = np.dot(b,c)
scalar_product_ac = np.dot(a,c)
print(scalar_product_ab)
print(scalar_product_bc)
print(scalar_product_ac)

34
68
4828


Случайные числа в NumPy

In [28]:
import numpy as np
np.random.rand()


0.29230932182123615

In [31]:
np.random.rand() * 100


98.7590620358213

In [32]:
np.random.rand(5)
# array([0.83745099, 0.58426808, 0.89206204, 0.41149807, 0.42445145])

array([0.48829675, 0.44736118, 0.37965088, 0.46347054, 0.04877573])

In [33]:
np.random.rand(2, 3)
# array([[0.94931212, 0.06680018, 0.26707599],
#      [0.67908873, 0.18001743, 0.97732239]])

array([[0.79690717, 0.45303244, 0.43583021],
       [0.23197782, 0.00811715, 0.51012022]])

In [36]:
np.random.rand(2, 2, 2, 2)

array([[[[0.35846612, 0.95785474],
         [0.50204563, 0.91827251]],

        [[0.00451954, 0.38440558],
         [0.90281041, 0.82150967]]],


       [[[0.88643412, 0.83596361],
         [0.35816463, 0.81817972]],

        [[0.62928038, 0.00404475],
         [0.60705278, 0.98642398]]]])

In [37]:
# чтобы передать в массив кортеж надо его распаковать
shape = (3, 4)
np.random.rand(*shape)
# array([[0.66169176, 0.19455777, 0.06451088, 0.31919608],
#        [0.73536951, 0.67104408, 0.4762727 , 0.88153576],
#        [0.70672971, 0.96677145, 0.09273995, 0.86356465]])

array([[0.38927923, 0.97543615, 0.14749011, 0.40208919],
       [0.19712137, 0.780368  , 0.43114201, 0.21649926],
       [0.40314634, 0.26132514, 0.4970654 , 0.16927918]])

In [57]:
# Но в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1, которая принимает в качестве аргумента именно кортеж без распаковки. Она называется sample:

shape = (2, 3)
np.random.sample(shape)
# array([[0.39756103, 0.01995168, 0.2768951 ],

array([[0.32539469, 0.6511063 , 0.75722709],
       [0.53517998, 0.96599891, 0.29461301]])

In [56]:
# Есть функция uniform
np.random.uniform(low=0.0, high=1.0, size=None)

0.5581292097507583

In [55]:
# Зададим границы диапазона от -30 до 50:
np.random.uniform(-30, 50)
# 38.47365525953661

36.005900818152824

In [42]:
# Получим пять чисел в интервале от 0.5 до 0.75:
np.random.uniform(0.5, 0.75, size=5)
# array([0.58078945, 0.58860342, 0.73790553, 0.63448265, 0.70920297])

array([0.58950501, 0.60459751, 0.70920057, 0.72955873, 0.60095095])

In [43]:
# Получим массив из двух строк и трёх столбцов из чисел в интервале от -1000 до 500:
np.random.uniform(-1000, 500, size=(2, 3))
# array([[ 129.22164163,   77.69090611, -132.9656972 ],
#        [  18.65802226, -317.14793906,   85.3613547 ]])

array([[-186.42752664, -723.79935863, -347.00777403],
       [  16.01693853, -879.1797657 , -117.1108629 ]])

Генерация целых чисел

In [ ]:
np.random.randint(low, high=None, size=None, dtype=int)

In [48]:
# Сгенерируем таблицу 2x3 от 0 до 3 включительно:

np.random.randint(4, size=(2,3))
# array([[3, 0, 1],
#       [2, 1, 3]])

array([[2, 1, 2],
       [3, 2, 1]], dtype=int32)

In [50]:
# Чтобы задать и нижнюю, и верхнюю границы самостоятельно, передадим два числа, а затем форму:
np.random.randint(6, 12, size=(3,3))
# array([[ 9,  6, 10],
#        [10, 11, 10],
#        [ 7, 10, 11]])

array([[10, 11, 10],
       [11, 10,  7],
       [ 8,  8, 11]], dtype=int32)

Генерация выборок

In [54]:
# Функция random.shuffle перемешивает тот массив, к которому применяется, и возвращает None.
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr
# array([0, 5, 1, 3, 2, 4])

[0 1 2 3 4 5]
None


array([4, 3, 1, 2, 5, 0])

In [ ]:
# Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation. Она принимает на вход один аргумент — или массив целиком, или одно число:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

# Обратите внимание, что необязательно передавать в функцию сразу массив: в этот раз мы передали в качестве аргумента список и ошибки не возникло. При этом на выходе получился уже 
# NumPy-массив (это заметно по отсутствию запятых при печати массива). Сам список playlist при этом остался без изменений.

['ACDC' 'Deep Purple' 'The Beatles' 'Pink Floyd']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [58]:
# Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n), где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.

np.random.permutation(10)
# array([7, 8, 2, 9, 4, 3, 1, 0, 5, 6])

# По сути, вначале создаётся массив из чисел с помощью arange, а затем он перемешивается. С помощью permutation можно избежать совершения этого дополнительного действия.

array([0, 1, 2, 9, 6, 7, 5, 3, 8, 4], dtype=int32)

In [61]:
# Чтобы получить случайный набор объектов из массива, используется функция random.choice:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Ivan' 'Nikita']


Seed генератора псевдослучайных чисел

In [72]:
# Зададим seed и посмотрим, что получится:

np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]], dtype=int32)

In [ ]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

In [ ]:
#Задание 9.6
import numpy as np
# Не забудьте импортировать numpy и сразу задать seed = 2021
np.random.seed(2021)
# В simple сохраните случайное число в диапазоне от 0 до 1
simple = np.random.rand()
# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их в переменную randoms
randoms = np.random.uniform(-150, 2021, size=120)
# Получите массив из случайных целых чисел от 1 до 100 (включительно) из 3 строк и 2 столбцов. Сохраните результат в table
table = np.random.randint(1, 101, size=(3,2))
# В переменную even сохраните четные числа от 2 до 16 (включительно)
even = np.arange(2, 17, 2)
# Скопируйте even в переменную mix. Перемешайте числа в mix так, чтобы массив изменился
mix = even.copy()
np.random.shuffle(mix)
# Получите из even 3 числа без повторений. Сохраните их в переменную select
select = np.random.choice(even, size=3, replace=False)
# Получите переменную triplet, которая должна содержать перемешанные значения из массива select (сам select измениться не должен)
triplet = np.random.permutation(select)
randoms






In [133]:
# Какие способы позволяют достоверно сравнить переменную elem с числом np.nan?

elem == np.nan

False

In [ ]:
#Задание 10.6
a=1
import numpy as np
def get_chess(a):
    chess = np.zeros((a,a))
    chess[1::2,::2] = 1
    chess[0::2,1::2] = 1
    chess.shape = (a,a)
    chess
    return chess
get_chess(a)

array([[0.]])

In [ ]:
#Задание 10.7
# Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. 
# Пользователю может настолько понравиться перемешанная 
# версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста, 
# а просто хотите сохранять тот seed, с которым он был сгенерирован.

# Для этого напишите функцию shuffle_seed(array), которая принимает на вход массив из чисел, генерирует случайное 
# число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив 
# (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

array = [1, 2, 3, 4, 5]
import numpy as np
def shuffle_seed(array):
    rand_seed = np.random.randint(0, 2**32, dtype=np.uint32)
    np.random.seed(rand_seed)
    mixed_array = np.random.permutation(array)
    return (mixed_array,rand_seed)

shuffle_seed(array)
    

(array([4, 1, 3, 2, 5]), np.uint32(1221171220))

In [ ]:
# Задание 10.8 Напишите функцию min_max_dist(*vectors), которая принимает на вход неограниченное число векторов через запятую. 
# Гарантируется, что все векторы, которые передаются, одинаковой длины.
# Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.


vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
vectors = (vec1,vec2,vec3)

import numpy as np
def min_max_dist(*vectors):
    distances = []
    n = len(vectors)
    for i in range(n):
        for j in range(i + 1, n):
            distance = np.linalg.norm(vectors[i] - vectors[j])
            distances.append(distance)
        min_dist = min(distances)
        max_dist = max(distances)
    return min_dist, max_dist

min_max_dist(*vectors)
    
    
    
    

(np.float64(5.196152422706632), np.float64(10.392304845413264))

In [ ]:
# Задание 10.9
# Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. 
# Гарантируется, что все векторы, которые передаются, одинаковой длины.
# Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.


import numpy as np
vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])

vectors = (vec1,vec2,vec3)
def any_normal(*vectors):
    n = len(vectors)
    for i in range(n):
        for j in range(i + 1, n):
            # Берем векторы по индексам i и j
            scalar_product = np.dot(vectors[i], vectors[j])
            if scalar_product == 0:
                return True
    return False
            
any_normal(*vectors)





True

In [ ]:
# Задание 10.9 версия 2
import numpy as np
vec1 = np.array([10, 0])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])

vectors = (vec1,vec2,vec3)
def any_normal(*vectors):
    n = len(vectors)
    for i in range(n):
        for j in range(i + 1, n):
            # Берем векторы по индексам i и j
            scalar_product = np.dot(vectors[i], vectors[j])
            if scalar_product == 0:
                return True
    return False
            
any_normal(*vectors)

False

In [ ]:
# Задание 10.10
# Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). 
# Это поля для игры в лото.
# Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).
# Функция возвращает полученный массив.
num=3
import numpy as np
def get_loto(num):
    np.random.randint(101, size=(num,5,5))
    return np.random.randint(101, size=(num,5,5))
get_loto(num)


array([[[ 25,  68,  49,  93,  78],
        [ 33,  58,  78,   2,  34],
        [ 81,  63,  34,  72,  41],
        [ 40,  77,  55,  27,  57],
        [  8,  49,  43,  75,  63]],

       [[ 96,  86,  47,  51,  67],
        [ 16,  11,  94,  96,  56],
        [ 20,  60,  99,  97,  13],
        [ 71,  38,  39,  43,  92],
        [ 69, 100,  51,  62,  28]],

       [[ 14,   9,  40,  99,  29],
        [ 94,  76,  92,  32,  78],
        [ 90,  37,  47,  59,  84],
        [ 13,  89,  58,  73,  22],
        [ 28,  46,  30,  96,  63]]], dtype=int32)

In [54]:
# Задание 10.11
# Напишите функцию get_unique_loto(num). Она так же, как и функция в задании 49.9.10, 
# генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.
# Функция также должна возвращать массив формы num x 5 x 5.


num=4
import numpy as np
def get_unique_loto(num):
    np.random.choice(101, size=(num,5,5), replace = False)
    return np.random.choice(101, size=(num,5,5), replace = False)
get_loto(num)

array([[[ 18,  86,  74,  60,  11],
        [ 96,  25,  72,   7,  37],
        [ 52,  87,  29,  36,  39],
        [ 44,  51,  19,  59,  15],
        [ 32,  98,  43,  38,  16]],

       [[ 61,  89,  79,   8,  82],
        [ 48,  83,  26,  47,  88],
        [ 90,  45,   5,  58,  23],
        [ 20,  66,   9,  77,  12],
        [ 55,   6,  40,  57,  24]],

       [[ 41,  68, 100,   0,  93],
        [ 13,  33,  10,  34,  50],
        [  2,  35,  71,   3,  14],
        [ 76,  46,  91,  22,  69],
        [ 94,  78,  42,  97,  49]],

       [[ 84,  27,  28,  63,  31],
        [ 30,  85,  65,  64,   4],
        [ 70,  99,  56,  80,  95],
        [ 21,  54,  81,  53,  75],
        [ 67,   1,  17,  73,  62]]], dtype=int32)

In [61]:
num=6
import numpy as np
def get_unique_loto(num):
  
    np.random.choice(np.random.permutation(101), size=(num,5,5), replace = False)
    return np.random.choice(np.random.permutation(101), size=(num,5,5), replace = False)

get_unique_loto(num)

ValueError: Cannot take a larger sample than population when 'replace=False'